- name: Generate CA private key
  shell: >
    openssl genrsa {{ ca_key_size }} > {{ ca_path }}/{{ ca_key }}

- name: Create CA certificate (self-signed)
  command: >
    openssl req -new -x509
    -nodes
    -key "{{ ca_path }}/{{ ca_key }}"
    -out "{{ ca_path }}/{{ ca_crt }}"
    -days "{{ ca_cert_days }}"
    -subj "/C={{ ca_country }}/ST={{ ca_state }}/L={{ ca_locality }}/O={{ ca_organization }}/OU={{ ca_org_unit }}/CN={{ ca_common_name }}"
